### ISSUE TITLE
Copy DLLs in build process

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unreal#10]
Probably will need to wait until UE 4.8, since it's this commit that makes it easier: https://github.com/EpicGames/UnrealEngine/commit/3a7e022d4cbdcd5faa1109b622c37f8a0118a900

**Comment by rpavlik** [comment]
Ok, so my pull request does include copying the DLLs, but it copies them with parallel structure - not to the executable directory.

There is a second, optional parameter to the `RuntimeDependency` constructor for `build.cs` files which appears to want an output filename, but there's no examples of its use in the engine codebase, and attempting to use it fails in interesting ways - suspect it wasn't tested. Looks like at least a few of the plugins I saw that use `RuntimeDependency` do their own "delay-load" work of effectively `GetProcAddress` which isn't very appealing given the C API.

Initial attempts to change the DLL path before letting the delay-loader kick in didn't work, didn't experiment further. Added the following at the indicated location in `OSVR.cpp` (with `Paths.h` added to the includes)

``` c++
void FOSVR::StartupModule()
{

#if (PLATFORM_WINDOWS && PLATFORM_64BITS)
    FString PlatformAbbrev = "Win64";
#elif PLATFORM_WINDOWS && PLATFORM_32BITS
    FString PlatformAbbrev = "Win32";
#endif
    auto DllDir = FPaths::GamePluginsDir() / FString("OSVR/Source/OSVRClientKit/bin/%s") / PlatformAbbrev;
    FPlatformProcess::AddDllDirectory(*DllDir);
```

**Comment by JeroMiya** [comment]
Implemented by https://github.com/OSVR/OSVR-Unreal/pull/46
