### ISSUE TITLE
Branch for 4.7 port

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unreal#11]
There's an interface that changed related to sceneview.

Not sure if we can do this behind ifdefs or if we should branch here. Also not sure about where focus should be allocated for each engine version.

**Comment by DuFF14** [comment]
This branch is working for me: https://github.com/OSVR/OSVR-Unreal/tree/ue4_7

**Comment by rpavlik** [comment]
Then perhaps document the branches in the README.
