### ISSUE TITLE
No headtracking

### ISSUE THREAD

**Issue by demonixis** [OSVR/OSVR-Unreal#112]
Hi,

I have no head tracking with Unreal 1.13 and the HDK 1.4.

![image](https://cloud.githubusercontent.com/assets/1017126/18174309/5de593ea-706d-11e6-87d2-93208e26505b.png)

I have created a new project (FPS) and enabled the OSVR plugin. When I try the VR preview, everything is working fine except the head tracking. I have the position tracking, I can control the player with my keyboard, but no head tracking.

OSVR: v0.6-1320-gc0575b0
GPU: Nvidia GTX 970 with latest drivers
OS: Windows 10 x64 Anniversary Update.

**Comment by JeroMiya** [comment]
From the server log it almost looks like there's an issue with the HDK hardware. Maybe file a support request?

**Comment by JeroMiya** [comment]
Hello again @demonixis, if you're still having this issue please let me know. It looks like it may be an HDK hardware issue. You can try updating the firmware to 1.98 or 1.99 and see if that helps - also at this point the master branch is really far ahead of the built-in plugin, so you may need to switch to source until we do a new code drop.

Closing this issue for now, but feel free to re-open it if it's still an issue with the latest graphics drivers, HDK firmware, and OSVR-Unreal source.
