### ISSUE TITLE
Infinite wait in FOSVRHMD.cpp

### ISSUE THREAD

**Issue by Kaluriel** [OSVR/OSVR-Unreal#127]
There is a flaw in the waiting for display loop in the constructor of FOSVRHMD. Currently it is using FDateTime::Now().GetSecond() which returns the current second of the minute, so it goes to 0 at instead of 60. So if you hit this with three seconds before the end of the current minute, it will never end (assuming it never succeeds).

Replace with
```
double now = FPlatformTime::Seconds();
const double end = now + 3.0f;

while (!bDisplayConfigOK && (now < end))
{
	bDisplayConfigOK = osvrClientCheckDisplayStartup(DisplayConfig) == OSVR_RETURN_SUCCESS;
	if (!bDisplayConfigOK)
	{
		bFailure = osvrClientUpdate(osvrClientContext) == OSVR_RETURN_FAILURE;
		if (bFailure)
		{
			UE_LOG(OSVRHMDLog, Warning, TEXT("osvrClientUpdate failed during startup. Treating this as \"HMD not connected\""));
			break;
		}
	}
	FPlatformProcess::Sleep(0.2f);

	now = FPlatformTime::Seconds();
}
```

**Comment by JeroMiya** [comment]
Thanks for reporting this!
