### ISSUE TITLE
osvrRenderManagerGetRenderInfoFromCollectionD3D11 return value assert

### ISSUE THREAD

**Issue by Kaluriel** [OSVR/OSVR-Unreal#138]
Every so often when I run a game, after a second or two osvrRenderManagerFinishPresentRenderBuffers fails, followed by an assert caused by the return value of osvrRenderManagerGetRenderInfoFromCollectionD3D11.
Nothing in the output windows from osvr library giving a clue apart from this.

> OSVRHMDLog:Warning: CheckUpdateFrameNumber: last update from a previous frame
> [2016.11.21-13.30.21:937][178]FOSVRCustomPresentLog:Warning: FDirect3D11CustomPresent::FinishRendering() - osvrRenderManagerFinishPresentRenderBuffers call failed.
> Assertion failed: rc == OSVR_RETURN_SUCCESS [File:d:\unreal\svnengine4_13\engine\plugins\experimental\osvr\source\osvr\private\OSVRCustomPresentD3D11.h] [Line: 151] 

Has anyone seen anything like this or can give a clue to what may be causing it? Guessing it is either threading or hardware related. It has been happening for the past few SDKs and hardware firmwares so I don't think it is anything new. Currently using osvr_server_config.HDK20DirectMode.sample.json with the HDK2

**Comment by Kaluriel** [comment]
Looks like this may have been a firmware issue, since updating to 1.99 this no longer occurs.

**Comment by JeroMiya** [comment]
Wonderful! Thanks for reporting! 1.98 and 1.99 seem to have fixed several issues for lots of OSVR users. Let us know if you have any other issues.
