### ISSUE TITLE
Parse and Implement Distortion

### ISSUE THREAD

**Issue by DuFF14** [OSVR/OSVR-Unreal#14]
Parsing would be done here: https://github.com/OSVR/OSVR-Unreal/blob/master/OSVRUnreal/Plugins/OSVR/Source/OSVR/Private/OSVRHMDDescription.cpp#L75

In Unity, it's implemented as a post process effect on each camera via this shader: https://github.com/OSVR/OSVR-Unity/blob/master/OSVR-Unity/Assets/OSVRUnity/Shaders/OsvrDistortion.shader

Need to look into how do this properly in Unreal. Looks like a shell for it here: https://github.com/OSVR/OSVR-Unreal/blob/f570b001265d7d9460afea6ed2206764923d11af/OSVRUnreal/Plugins/OSVR/Source/OSVR/Private/OSVRRender.cpp#L25

Related to https://github.com/OSVR/OSVR-Unreal/issues/2

**Comment by payalord** [comment]
Location of Unity "OsvrDistortion.shader" has been changed: https://github.com/OSVR/OSVR-Unity/blob/master/OSVR-Unity/Assets/OSVRUnity/Resources/OsvrDistortion.shader

**Comment by rpavlik** [comment]
And the display code could be mostly ripped out, now that we have the display and display input APIs in OSVR Core.

**Comment by payalord** [comment]
As i understand you guys looking something like this? http://eat3d.com/free/ue4-shader-fx-cubic-lens-distortion

**Comment by JeroMiya** [comment]
This is now implemented in RenderManager.
