### ISSUE TITLE
Pointer set to null before access

### ISSUE THREAD

**Issue by Kaluriel** [OSVR/OSVR-Unreal#141]
I forgot to plug in the HDK2 (I had the USB since I did the firmware update to 1.99, but the HDMI wasn't plugged in) and hit a null pointer at [line 158 of OSVRRender.cpp](https://github.com/OSVR/OSVR-Unreal/blob/master/OSVRUnreal/Plugins/OSVR/Source/OSVR/Private/OSVRRender.cpp#L158). 
Appears to be caused by [line 152 in the same file](https://github.com/OSVR/OSVR-Unreal/blob/master/OSVRUnreal/Plugins/OSVR/Source/OSVR/Private/OSVRRender.cpp#L152).

To work around it I just redid the logic so the original behaviour if null gets triggered

```
if (mCustomPresent)
{
	if (!mCustomPresent->IsInitialized() && IsInRenderingThread() && !mCustomPresent->Initialize())
	{
		mCustomPresent = nullptr;
	}
}

if (mCustomPresent)
{
       // this only happens once, the first time this is called. I don't know why.
       if (IsInRenderingThread())
       {
           mCustomPresent->LazyOpenDisplay();
           mCustomPresent->CalculateRenderTargetSize(InOutSizeX, InOutSizeY, screenScale);
       }
...
```

**Comment by JeroMiya** [comment]
Fixed by: https://github.com/OSVR/OSVR-Unreal/pull/142

Thanks for the report!
