### ISSUE TITLE
Split into two modules

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unreal#18]
Right now, there is an ifdef since each module appears to be limited to implementing one interface, so it can either be an HMD interface (which is not strictly true, since theoretically we aren't limiting ourselves to HMDs), or an input interface. What the SteamVR plugin in 4.8 does, and what we should do, is have two modules, that share the necessary state (in this case, the client context), but with one implementing one module interface (HMD module) and the other implementing the other module interface (input interface module).

**Comment by JeroMiya** [comment]
Implemented by https://github.com/OSVR/OSVR-Unreal/pull/50
