### ISSUE TITLE
Re-arrange branches

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unreal#19]
Right now, master is ue 4.6, then we have branches for 4.7 and 4.8. Not sure if this goes in the readme or the wiki for this project (we can turn it back on if we want)

**Comment by OlafHaag** [comment]
Hey there, Ryan! Is there any documentation for the osvr unreal plugin? This link didn't work: https://github.com/OSVR-Unreal/blob/master/OSVR%20Unreal%20Plugin.pdf (provided by https://osvr.github.io/build-with/)
I'll need some overview on what to do after cloning. My goal is to get data from an external VRPN tracker device/server into unreal and be able to access it via bluprints if possible.

**Comment by rpavlik** [comment]
Ah, good catch. The documentation was turned into markdown format, which you should be able to read online on github (in the file named documentation.md)

I'll file an issue to fix the web site link.

Follow up questions, etc, since they don't really relate to describing the branches (this issue), might be better posted on the dev mailing list - more people will see it, etc.

**Comment by rpavlik** [comment]
Branches should match unreal engine itself.

**Comment by JeroMiya** [comment]
Master is now 4.9, which is an updated version of the previous 4.8 branch. Added a 4.6 branch with previous master. All other branches remain the same.
