### ISSUE TITLE
adjust rendering from JSON

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unreal#2]
Apparently does this somewhat already - so will likely need to be adjusted when the schema changes.

Apparently relevant files:
- https://github.com/OSVR/OSVR-Unreal/blob/master/OSVR/Source/OSVR/Private/OSVRHMDDescription.h
- https://github.com/OSVR/OSVR-Unreal/blob/master/OSVR/Source/OSVR/Private/OSVRHMDDescription.cpp
- https://github.com/OSVR/OSVR-Unreal/blob/master/OSVR/Source/OSVR/Private/OSVRRender.cpp

Note that it looks like it might be hooking in to some existing HMD-specific code in Unreal, which we may or may not want.

**Comment by DuFF14** [comment]
This has been partly addressed here: https://github.com/OSVR/OSVR-Unreal/pull/13
Still need to parse distortion (and implement), which has its own issue: https://github.com/OSVR/OSVR-Unreal/issues/14
