### ISSUE TITLE
Port to OSVR-Core display API

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unreal#21]
Hopefully we can just provide a similar display model, instead of having to somehow shoehorn it in to the `IHeadMountedDisplay` which looks more like an `IOculusRift` or `IVive` than an actual generic VR display interface.

**Comment by JeroMiya** [comment]
Pull request up for this issue: https://github.com/OSVR/OSVR-Unreal/pull/28

**Comment by JeroMiya** [comment]
This is now in master.
