### ISSUE TITLE
Investigate latency

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unreal#22]
On my machine, I was getting an estimated 250ms latency in the demo app, which is a lot of overhead for Unreal to be adding. Could be my graphics card or general system load, or system settings, but the "out of box experience" for the integration should be better.

**Comment by JeroMiya** [comment]
Some latency was reduced with this issue fixed:
https://github.com/OSVR/OSVR-Unreal/issues/7

This causes some performance overhead, but apparently not as much as it did pre-4.8. The current rift plugin turns this setting off. I only see a 1-2ms difference in frame render time (according to profilegpu), but this is with a small scene.

The next biggest source of latency for me is likely to be from me running the HDK in landscape mode with my main display duplicated.

Next, @yboger suggested running context update more than once per frame, and closer to frame render time. Couldn't hurt, but I think adding render manager support w/direct mode is going to give the biggest gain.

Frame render time doesn't appear to be a significant factor in latency. I am getting consistent 4-6ms frame render times. Granted this is with a very simple scene - I could import a more complex map from the gallery for testing purposes to see for sure, but it's not a priority.

**Comment by JeroMiya** [comment]
Closing this as we are doing much better with latency in the latest code (this is an old issue).
