### ISSUE TITLE
Image cross-talk on beginning and end lines of display

### ISSUE THREAD

**Issue by MulanVR** [OSVR/OSVR-Unreal#31]
Not obvious if you don't have -2 diopters at least, but the first and last vertical lines of the display get cross talk in some specific contrast. 

When running unreal demos it looks like the screen resolution looses a few lines on each end which will look black. However when a high contrast object on a black background will go out of the visual field on one side, you may notice that the side black lines on the other side will show what looks like a reflection on the opposite side. Initially thought to be a reflection on the body material and center separator, it has been confirmed to be on the display instead.

We have noticed this issue on 2-3 unreal recent demos. Easiest to reproduce with the latest version of Showdown (look at the solid 3D logo at the center and drive it half off your visual filed of view moving your head sideways).

**Comment by JeroMiya** [comment]
@MulanVR Do you still have this issue with the latest HDK firmware?

Going to close this issue for now, but feel free to re-open it if you're still having issues (we may move it over to support or a different repo as it appears to be hardware related rather than OSVR-Unreal specific?).
