### ISSUE TITLE
fatal error c1083 'D3D11RHIBasePrivate.h': No such file or directory

### ISSUE THREAD

**Issue by typhoidcoma** [OSVR/OSVR-Unreal#44]
Has anyone run across this issue when compiling the OSVR plugin?  Everything seems fine and the file does exist.  I can't figure out what's going on.  Thanks for any suggestions or help!

Log:

 Performing 21 actions (4 in parallel)
1>  PCH.OSVRPrivatePCH.h.cpp
1>  PCH.UELinkerFixupsName.h.cpp
1>  PCH.ex_machina.h.cpp
1>  UELinkerFixups.cpp
1>  ex_machinaGameMode.cpp
1>  ex_machina.cpp
1>  ex_machina.generated.cpp
1>  OSVRInputDevice.cpp
1>  OSVRInterface.cpp
1>  OSVRRender.cpp
1>  OSVRInterfaceCollection.cpp
1>  OSVRInputComponent.cpp
1>  OSVRHMDDescription.cpp
1>D:\Epic Games\4.10\Engine\Source\Runtime/Windows/D3D11RHI/Private/D3D11RHIPrivate.h(20): fatal error C1083: Cannot open include file: 'D3D11RHIBasePrivate.h': No such file or directory
1>  OSVRHMD.cpp
1>  OSVREntryPoint.cpp
1>  OSVRBPFunctionLibrary.cpp
1>  OSVRActor.cpp
1>  OSVR.cpp
1>D:\Epic Games\4.10\Engine\Source\Runtime/Windows/D3D11RHI/Private/D3D11RHIPrivate.h(20): fatal error C1083: Cannot open include file: 'D3D11RHIBasePrivate.h': No such file or directory
1>  OSVR.generated.cpp
1>D:\Epic Games\4.10\Engine\Source\Runtime/Windows/D3D11RHI/Private/D3D11RHIPrivate.h(20): fatal error C1083: Cannot open include file: 'D3D11RHIBasePrivate.h': No such file or directory
1>D:\Epic Games\4.10\Engine\Source\Runtime/Windows/D3D11RHI/Private/D3D11RHIPrivate.h(20): fatal error C1083: Cannot open include file: 'D3D11RHIBasePrivate.h': No such file or directory
1>  -------- End Detailed Actions Stats -----------------------------------------------------------
1>ERROR : UBT error : Failed to produce item:

**Comment by typhoidcoma** [comment]
Quick and stuppid update.  I had to move the files out of a "windows" folder into here:

Epic Games\4.10\Engine\Source\Runtime\Windows\D3D11RHI\Private\Windows

to

Epic Games\4.10\Engine\Source\Runtime\Windows\D3D11RHI\Private\

It works but its a hack, will need to update the header locations.

**Comment by JeroMiya** [comment]
Yes, this is because we must use a private unreal module and we end up needing to hard code the full path to those d3d11 headers. If you look at the plugin's build file, you'll see two hard coded full paths being added to the private include search path. As a temporary workaround, you can modify these to point to your unreal installation.

**Comment by typhoidcoma** [comment]
Fantastic, thanks a bunch for the info!

**Comment by JeroMiya** [comment]
No problem! Thanks for the report. I am hoping to improve the experience a bit in the future, so that you can install the plugin globally.
