### ISSUE TITLE
Don't require importing of OSVR-Core source

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Unreal#5]
This plugin should be able to build against just a binary release of OSVR - no need to re-compile the core. Not sure if there's some way to generate the Unreal-specific project files with CMake, but if so that's the easiest, and most cross-platform, way.

**Comment by kafumanto** [comment]
Currently the "plugin" is the `OSVR/` directory. To let Unreal find the files needed to properly compile & run the plugin, you have to run the `OSVR/ThirdParty/OSVR/ImportFromSDK.bat` script. That batch file expects the Windows binary releases of OSVR-Core for both 32 and 64 bits architectures (the 64 bits version is used by the Unreal **editor**, the 32 bits is used when Unreal builds a **shipping** version of your project); no source code or recompilation of OSVR-Core is needed. The batch file copies and reorganises the binary files as required by Unreal (Unreal picks the files from pre-defined directories). At that point the `OSVR/` plugin is ready to be used as described by `Documentation.md`.

If you have binaries for other operating systems, you can edit the `LoadOSVRLib` function in `OSVR/Source/OSVR/OSVR.Build.cs` to enable them in Unreal; provided you place the needed binaries where expected (see the `ImportFromSDK.bat` file).

**Comment by rpavlik** [comment]
I see I was mistaken, and was just confused about the generated files being included in the repo. I went down the rabbit-hole with Unreal some time ago and cleaned things up, hopefully streamlining it. This is no longer an issue.
