### ISSUE TITLE
Disable all blueprint functionality behind #ifdefs

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Unreal#58]
On a review of the current OSVR-Unreal blueprint functionality, it has become apparent that there may be some design issues, such as only supporting a pre-determined list of paths for some blueprint callable functions. Before too many people start to rely on those functions, we should disable them until a more thorough review and perhaps redesign of the blueprint library can be done.

**Comment by JeroMiya** [comment]
Implemented in https://github.com/OSVR/OSVR-Unreal/pull/59 

I decided to move the deprecated code to `/Archive` instead of wrapping the functionality in ifdefs. Cleaner that way, and avoids issues with the unreal header tool.

**Comment by OlafHaag** [comment]
Does this mean, that if I used OSVR Blueprint nodes get data from our motion capture system via VRPN configuration, that this won't work anymore? Do I have to use C++ now, which I know very little about?

**Comment by JeroMiya** [comment]
I kept the code around in /Archive just in case people still need it. However, there is some code I had to comment out in OSVREntryPoint.cpp, so reopening this issue to wrap the disabled code in a flag to make it easier for people to continue using the BP API.

When this is done, you should be able to copy the code from /Archive back into /OSVRUnreal in your local copy (I kept the same directory structure to make it easier) and set a flag to enable it.

**Comment by JeroMiya** [comment]
@Vaquero84 OK, I made it a little easier to re-enable the blueprint API. See the note at the end of `Documentation.md`: https://github.com/OSVR/OSVR-Unreal/blob/master/Documentation.md

**Comment by OlafHaag** [comment]
Thank you very much!
