### ISSUE TITLE
4.10 Compiling Issue

### ISSUE THREAD

**Issue by CJRobertson** [OSVR/OSVR-Unreal#67]
Howdy there!

I'm having an issue with the plugin being compiled that I cannot for the life of me figure out. The error log says there are a few files from the ClientKit folder that cannot be found because they are missing or don't exist. If I look in the folder though all the required files are there; I also made sure to copy over everything to the binaries folders, etc. as the READ ME suggests but still no go. I've checked all the pathing in the code and it all seems correct so unless there is something I'm missing then I'm totally stumped and there is no reason for it not to work.

Currently I'm using the newest 4.10.4 release but I've had this problem since 4.10.2 and I'm also using the newest version of the Core SDK, the Render Manager and the OSVR-Unreal plugin. Before it is asked, I followed the instructional video exactly as instructed so that does not help this situation since it was done exactly as needed. 

[OSVR_4.10_CompileErrorLog.txt](https://github.com/OSVR/OSVR-Unreal/files/143947/OSVR_4.10_CompileErrorLog.txt)

**Comment by JeroMiya** [comment]
Could you try regenerating the visual studio project one more time? Maybe delete the generated project/solution files completely and start from scratch.

**Comment by CJRobertson** [comment]
Check this out.

As you saw in the log it failed to compile and I have been having this issue for a long time. I tried your suggestion multiple times in the past with no luck and I've tried different SDK versions, recompiling, blah blah and guess what? I did the exact same thing as I've always done to reproduce the error and now it compiles just fine. I don't know what changed but now all of a sudden it works and I wish I knew why...

This MIGHT be related to why others have issues as well.

**Comment by CJRobertson** [comment]
Sadly I don't have an OSVR to test it out on currently so I'm stuck wondering if it actually works or if it's faking it. Guess I could fake the input myself but I wouldn't know if the rendering is working correctly or anything :( Been mainly working with Google Cardboard since that's a heavily requested feature on UE4 and using the OSVR SDK for Cardboard would be an awesome way to showcase the SDK.

**Comment by JeroMiya** [comment]
I've experienced some Unreal build system stickiness sometimes as well. It's generally pretty good, but sometimes I have to close everything down, delete the generated files, and start fresh to get it unstuck.

FYI: you can check the rendering without an OSVR by using one of the extended mode server configurations. You can modify the window position and size as you like (the default puts up a 1080p window 1920 pixels to the right of the top left of the main screen). You should see the distorted side-by-side image in a window when you run the render manager samples.

Well, actually, you would still need an alias mapped to /me/head that generates tracker reports regularly. I've been meaning to write a dummy tracker plugin for this purpose but haven't gotten around to it. In the meantime, you could write your own if you like - there are some sample plugins in OSVR-Core. It's pretty straightforward.

**Comment by tobkum** [comment]
@CJRobertson I had the same problem when I extracted the plugin to a directory containing spaces. Then those files will not be copied, and the compilation will fail. As soon as the plugin resides in a space-less directory, the ImportFromSDK.cmd works fine.
