### ISSUE TITLE
FOV settings

### ISSUE THREAD

**Issue by SFR75** [OSVR/OSVR-Unreal#69]
I can seems to change FOV settings. (neither from ~ console, nor from the code).
The FOV remains fixed no matter what (and wide!)

**Comment by JeroMiya** [comment]
The FOV comes from the display descriptor of the HMD and can't be changed from the plugin. When stereo rendering in OSVR is enabled, the FOV should match the hardware you are using, otherwise the projection will be incorrect (and you'll probably make your users a little sick).
