### ISSUE TITLE
setting up VR with Unreal

### ISSUE THREAD

**Issue by s4rda** [OSVR/OSVR-Unreal#74]
Hello I am following the instructions on the youtube video on how to set up my OSVR to unreal and when I hit File -> Generate Visual Studio Project. It gives me this error
Running C:/Program Files (x86)/Epic Games/4.11/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="C:/Users/sergio/Desktop/VR Files/OSVR-Unreal-master/OSVR-Unreal-master/OSVRUnreal/OSVRUnreal.uproject" -game -progress -2015
Visual C++ 2015 toolchain does not appear to be correctly installed. Please verify that "Common Tools for Visual C++ 2015" was selected when installing Visual Studio 2015.
Discovering modules, targets and source code for game...
UnrealBuildTool Exception: ERROR: Windows SDK v8.1 must be installed in order to build this target.

what should I do about this?

**Comment by chase-cobb** [comment]
Click the Windows start button, search for and open "Programs and Features". Select your version of Visual Studio in that list and click "Change". This will allow you to install the missing components for Visual Studio that UE4 requires.

That should fix your issue.

**Comment by JeroMiya** [comment]
I'm going to go ahead and close this, but feel free to re-open if you're still experiencing this issue with the latest version of Unreal and OSVR-Unreal.
