### ISSUE TITLE
VR using plugin not working in UE4Editor or build, giving "OSVR client context did not initialize correctly" error

### ISSUE THREAD

**Issue by Stormwind99** [OSVR/OSVR-Unreal#78]
In the prebuilt OSVR Unreal Plugin distributed with UE4.12.5, we can't get Preview in VR in UE4Editor or VR in a Shipping build working with OSVR.

UE4 always gives following error:
`OSVREntryPointLog:Warning: OSVR client context did not initialize correctly. Most likely the server isn't running. Treating this as if the HMD is not connected.`

The OSVR Server is running, and the Unity-based Palace demo displays properly on the VR headset (an HDK2) before and after trying it in Unreal.

To make sure it wasn't our project causing the issue, we also tried using the VRContentExamples project from https://github.com/mitchemmc/VRContentExamples - enabling the OSVR Plugin from the VR category in the Plugins window, but it didn't work either.

**Comment by JeroMiya** [comment]
Could you try running the latest plugin from source and see if that addresses the issue? You'll need to disable the prebuilt plugin and add OSVR as a local plugin to your project. The prebuilt plugin is a couple of months old. We have submitted an update but I don't know when the update will ship.

**Comment by Stormwind99** [comment]
Trying it now.

The ImportFromSDK.cmd script (from setup steps) asks for the DirectRender 64bit SDK root dir but I can't find that SDK anywhere.   Do you know where that is?

**Comment by Stormwind99** [comment]
ImportFromSDK.cmd doesn't seem to work correctly currently against latest SDK, etc. so following the build instructions from README.md doesn't work.

I think paths to files to copy may have changed, breaking ImportFromSDK.cmd .

I'm using OSVR-Unreal master branch.

The fewest errors occur when I use command line (parameter 3 for DirectRender SDK seems wrong);

```
ImportFromSDK.cmd "C:\Program Files (x86)\OSVR\SDK" "C:\Program Files\OSVR\SDK" "C:\Program Files\OSVR\SDK\bin" "D:\Dev\osvr-android-ndk"
```

Errors:

```
File not found - RenderKit
0 File(s) copied
The system cannot find the file specified.

File not found - osvrRenderManager.lib
0 File(s) copied
The system cannot find the file specified.
```

**Comment by Stormwind99** [comment]
I fixed ImportFromSDK.cmd so it works now (and will submit a pull request).  I then rebuilt the OSVR-Unreal plugin from master branch of the repo and switched my project to use it, but I still get the same error and no VR:

`OSVREntryPointLog:Warning: OSVR client context did not initialize correctly. Most likely the server isn't running. Treating this as if the HMD is not connected.`

Update: the pull request is https://github.com/OSVR/OSVR-Unreal/pull/79

**Comment by Stormwind99** [comment]
More data points:
1. The example OSVRUnreal.uproject gets the same error in UE4Editor, and usually has VR Preview disabled.  
   - _But_ the few times when VR Preview is available, it gets the same error when PIE (Play in Editor) is attempted.  
   - Except it worked _once_ out of over 25 tries - which I think increases probability of a timing related bug.   That one time it worked the demo displayed in the HDK2 HMD.
2. The pre-built Showdown VR demo also gets the same error, then crashes.

The error:
`OSVREntryPointLog:Warning: OSVR client context did not initialize correctly. Most likely the server isn't running. Treating this as if the HMD is not connected.`

In my project's case, the OSVR-Unreal plugin is failing when calling osvrClientCheckStatus() and osvrClientUpdate() in the initialization process - which is what causes that error to be displayed and OSVR support to fail.

**Comment by godbyk** [comment]
Does the server indicate that a client has connected when you start the game?

**Comment by Stormwind99** [comment]
Yes, I see the following messages from the OSVR Server when UE4Editor or UE4 starts up and loads the project:

```
vrpn: Connection request received from 127.0.0.1: 127.0.0.1 51885
July 31 21:48:05.357 info [OSVR Server]: Performing hardware auto-detection.
July 31 21:48:10.546 info [OSVR Server]: Sent path tree to clients.
July 31 21:48:10.546 info [OSVR Server]: Performing hardware auto-detection.
July 31 21:48:10.705 info [OSVR Server]: Sent path tree to clients.
```

**Comment by godbyk** [comment]
It sounds like the client–server connection is okay then. (You can confirm this with the `osvr_print_tree` utility. If it prints out the tree, it can talk to the server.)

The error message you mentioned [above](https://github.com/OSVR/OSVR-Unreal/issues/78#issuecomment-236403118) indicates that Unreal couldn't connect to the server within three seconds. If it's connecting occasionally, you might try increasing the timeout in [OSVREntryPoint.cpp](https://github.com/OSVR/OSVR-Unreal/blob/master/OSVRUnreal/Plugins/OSVR/Source/OSVR/Private/OSVREntryPoint.cpp#L40) to see if it eventually connects.

**Comment by Stormwind99** [comment]
osvr_print_tree works.

I'm having mixed results with increasing the timeout in OSVREntryPoint.cpp .  

The OSVRUnreal.uproject file works more frequently in VR Preview.   Other projects have same problem or crash - see https://github.com/OSVR/OSVR-Unreal/issues/80

**Comment by Stormwind99** [comment]
Increasing the timeout in OSVREntryPoint.cpp worked - but I do worry about it slowing the UE4 startup for projects that run in OSVR, non-OSVR VR, and non-VR environments.

**Comment by JeroMiya** [comment]
Yes, this was a concern of mine as well. Unreal's VR plugin system doesn't have an "async" way of determining connectivity status for a particular plugin, so we have to block while we wait for the server to connect. I'll look into adding some timing to the startup code so that we can at least get a good feel for the optimal timeout period.

**Comment by Stormwind99** [comment]
Related to this, I previously submitted a request to Epic for UE4 command line options to force a specific VR API (or none) to avoid problems like auto-detect choosing the wrong VR API (compared to user's selection from Steam or other front-end) and unneeded startup delays.

https://udn.unrealengine.com/questions/305191/auto-detection-of-vr-api-can-override-users-select.html
