### ISSUE TITLE
Windows 7 machines give dxgi.dll error on UE4 startup with OSVR-Unreal enabled

### ISSUE THREAD

**Issue by Stormwind99** [OSVR/OSVR-Unreal#99]
Windows 7 machines give dxgi.dll error on UE4 startup with OSVR-Unreal enabled, even though dxgi.dll is present on the machine.

Machine that worked: dxgi.dll version 10.0.10586.494 modified 6/30/2016, Windows 10
Machine with error: dxgi.dll version 6.2.9200.16492 modified 1/13/2013, Windows 7 with Platform Update installed

UE4 and our full game builds work on the same machine fine without the error if OSVR-Plugin is not present or disabled.   Other UE4 VR plugins enabled do not give the error on same machine.

I'm guessing the OSVR SDK binaries were built and linked against the newer dxgi.dll .   From a quick grep, I suspect osvrRenderManager.dll or SDL2.dll .

**Comment by JeroMiya** [comment]
Do the render manager samples give the same error?

**Comment by JeroMiya** [comment]
Ah, nevermind. Looks like a known issue:
https://github.com/sensics/OSVR-RenderManager/issues/162

Closing this issue, but please note progress on that issue.

**Comment by truegeorg** [comment]
Link not work
